spring:
  application:
    name: calog

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sbb_dev
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
            extract: TRACE
