spring:
  application:
    name: calog

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/info_share
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
        show_sql: true
  profiles:
    include: secret

  jackson:
    time-zone: UTC

# 추가: Security 설정 파일 포함

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
            extract: TRACE
